service: autonomia-api-leadshot

frameworkVersion: '3'

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api-leadshot.autonomia.site
    basePath: ''
    stage: ${opt:stage, 'prod'}
    certificateId: 'cee74474-da0c-4aba-b9f7-3759e4eddd7e'
    createRoute53Record: false
    endpointType: 'edge'
  authorizer:
    name: cognitoAuthorizer
    type: COGNITO_USER_POOLS
    identitySource: method.request.header.Authorization
    arn: !ImportValue autonomia-api-auth-${self:provider.stage}-UserPoolArn

layers:
  commonLibs:
    path: layers/common
    name: ${self:service}-${self:provider.stage}-common
    compatibleRuntimes:
      - nodejs18.x
    package:
      include:
        - node_modules/pg/**
        - node_modules/knex/**
        - node_modules/ioredis/**

package:
  individually: true
  patterns:
    - '!**/*.map'
    - '!**/*.md'
    - '!test/**'
    - '!tests/**'
    - '!**/.env*'
    - '!package-lock.json'
    - '!**/.npmrc'
    - '!node_modules/**'
    - '!dist/**'
    - '!layers/**'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  memorySize: 512
  timeout: 30
  vpc:
    securityGroupIds:
      - 'sg-0e9189ca9e6d0427d'
    subnetIds:
      - 'subnet-07184b6cfa97367e2'
      - 'subnet-000fbcffe0f8d9a11'
  environment:
    NODE_ENV: ${opt:stage, 'prod'}
    DB_HOST: ${ssm:/autonomia/${self:provider.stage}/db/host, 'autonomia-prod-db.cde6ocsqc6dk.us-east-1.rds.amazonaws.com'}
    DB_PORT: ${ssm:/autonomia/${self:provider.stage}/db/port, '5432'}
    DB_NAME: ${ssm:/autonomia/${self:provider.stage}/db/name, 'autonomia_db'}
    DB_USER: ${ssm:/autonomia/${self:provider.stage}/db/user, 'autonomia_admin'}
    DB_PASSWORD: ${ssm:/autonomia/${self:provider.stage}/db/password, ''}
    DB_SSL_ENABLED: ${ssm:/autonomia/${self:provider.stage}/db/ssl-enabled, 'false'}
    REDIS_HOST: ${ssm:/autonomia/${self:provider.stage}/redis/host, ''}
    REDIS_PORT: ${ssm:/autonomia/${self:provider.stage}/redis/port, '6379'}
    CACHE_TTL: ${ssm:/autonomia/${self:provider.stage}/cache/ttl, '300'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds:*
      Resource: "*"
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "arn:aws:ssm:us-east-1:*:parameter/autonomia/*"
    - Effect: Allow
      Action:
        - elasticache:*
      Resource: "*"

functions:
  # Template Message
  listTemplateMessages:
    handler: handlers/list-template-messages.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/TemplateMessages
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                accountId: true
          authorizer: ${self:custom.authorizer}

  getTemplateMessage:
    handler: handlers/get-template-message.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/TemplateMessages/{templateMessageId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                templateMessageId: true
          authorizer: ${self:custom.authorizer}

  createTemplateMessage:
    handler: handlers/create-template-message.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/TemplateMessages
          method: post
          cors: true
          authorizer: ${self:custom.authorizer}

  updateTemplateMessage:
    handler: handlers/update-template-message.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/TemplateMessages/{templateMessageId}
          method: put
          cors: true
          request:
            parameters:
              paths:
                templateMessageId: true
          authorizer: ${self:custom.authorizer}

  # Message Logs
  createMessageLog:
    handler: handlers/create-message-log.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/MessageLogs
          method: post
          cors: true
          authorizer: ${self:custom.authorizer}

  # Chat Memory
  createChatMemory:
    handler: handlers/create-chat-memory.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/ChatMemory
          method: post
          cors: true
          authorizer: ${self:custom.authorizer}

  # Campaigns
  listCampaigns:
    handler: handlers/list-campaigns.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/Campaigns
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                productId: true
          authorizer: ${self:custom.authorizer}
  createCampaign:
    handler: handlers/create-campaign.handler
    layers:
      - { Ref: CommonLibsLambdaLayer }
    events:
      - http:
          path: Autonomia/Leadshot/Campaigns
          method: post
          cors: true
          authorizer: ${self:custom.authorizer}
